stages:
    - build

full:

  stage: build
  
  image: rootproject/root-conda

  script:
    - echo $CI_USER_PASSWORD | kinit $CI_USER@CERN.CH
    - export SRC="l0mdt_buses.csv"
    - git pull origin $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - wget --output-document=$SRC "https://docs.google.com/spreadsheets/d/e/2PACX-1vSylQoq9qcxKz2dhXTtZpDkz00jicsuqYw_u6hopU_zs0gtBy5pBBD10hlvqPQ6ShLH5MP3eNKenzAO/pub?gid=1745105770&single=true&output=csv"
    - export REPO=`echo $CI_PROJECT_URL | sed -e s#https://##`
    - git remote set-url origin https://${CI_USER}:${CI_PUSH_TOKEN}@$REPO.git
    - git config user.email ${CI_EMAIL}
    - git config user.name ${CI_USER}
    - git add $SRC
    - git commit -m "CSV updated $(date +'%Y-%m-%d %H:%M:%S')" 
        && git push origin $CI_COMMIT_REF_NAME
        && git push origin :refs/tags/csv
        && git tag --force csv
        && git push origin csv
        || true
    - export CSV_SHA=$(git rev-parse --quiet --verify csv)
        || git push origin :refs/tags/csv
        && git tag --force csv
        && git push origin csv
        && export CSV_SHA=$(git rev-parse --quiet --verify csv)
    - python l0mdt_dataFormat.py -i l0mdt_buses.csv -r "${CSV_SHA}"
    - git add *.h *.svh *.vhd l0mdt_buses_latex/*.csv
    - git commit -m "Output files updated $(date +'%Y-%m-%d %H:%M:%S')"
        && git push origin $CI_COMMIT_REF_NAME
        || exit 0


