build:
  image: "python:3.8"
  stage: build
  script:
    - python --version
    - wget --output-document=l0mdt_buses.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vSylQoq9qcxKz2dhXTtZpDkz00jicsuqYw_u6hopU_zs0gtBy5pBBD10hlvqPQ6ShLH5MP3eNKenzAO/pub?gid=1745105770&single=true&output=csv"
    - pwd
    - ls -l
    - python l0mdt_dataFormat.py -i l0mdt_buses.csv
  artifacts:
   when: on_success
   paths:
    - l0mdt_buses.sv
    - l0mdt_buses.vhdl
    - l0mdt_buses.h
    - l0mdt_buses_constants.sv
    - l0mdt_buses_constants.vhdl
    - l0mdt_buses_constants.h

deploy:
  stage: deploy
  before_script:
    -  env
    -  export REPO=`echo $CI_PROJECT_URL | sed -e s#https://##`
    -  git remote set-url origin https://${CI_USER}:${CI_PUSH_TOKEN}@$REPO
    -  git config --global user.email ${CI_EMAIL}
    -  git config --global user.name ${CI_USER}
    -  echo "after config user name"
    -  git fetch
    -  git fetch origin $CI_COMMIT_REF_NAME    
    -  git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    -  git checkout $CI_COMMIT_REF_NAME
    -  echo $CI_USER_PASSWORD | kinit $CI_USER
 # before_script:
 #   - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
 #   - eval `ssh-agent -s`
 #   - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/authorized_keys
 #   - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh ke
 #   - mkdir -p ~/.ssh
 #   - echo "after mkdir"
 #   - chmod 700 ~/.ssh
 #   - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
 #   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git add -f *.sv *.vhdl *.h
    - git commit -m "Compiled PDF from $CI_COMMIT_SHORT_SHA [skip ci]" || echo "No changes, nothing to commit!"
    #- git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    #- git push origin HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger
    - git push
